config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users, :controllers => {
                       registrations: 'registrations',
                   :omniauth_callbacks => 'omniauth_callbacks'}

  resources :users do
    resources :posts
    resources :voices
    resources :revisions
    resources :collections
    resources :addresses
  end

  resources :orders do
    resources :cards
  end

  resources :cards do
    resources :addresses
    collection {post :import}
  end

  resources :rankings

  resources :task_lists do
    resources :tasks
  end

  resources :calendars
  resources :charges

  resources :sources, only: [:create, :destroy, :index]
  resources :collection_items, only: [:create, :destroy, :index]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :messages do
    member do
      match 'mark_as_read', :to => 'messages#mark_as_read', via: :put
      match 'archive', :to => 'messages#archive', via: :put
      match 'mark_as_new', :to => 'messages#mark_as_new', via: :put
    end
  end
  resources :trends
  resources :users do
    member do
      match 'toggle' => 'users#toggle', via: :put
    end
  end

  resources :relationships, only: [:create, :destroy]

  match 'favorites', :to => 'favorites#index', via: :get

  resources :categories do
    resources :posts
    member do
      match 'upvote' => 'categories#upvote', via: :put
      match 'downvote' => 'categories#downvote', via: :put
      match 'publish' => 'categories#publish', via: :put
    end
  end

  match 'welcome', to: 'static_pages#welcome_registration', via: :get
  match 'analytics', to: 'static_pages#analytics', via: :get


  match 'manage', to: 'posts#manage', via: :get

  resources :posts do
    member do
      match 'upvote' => 'posts#upvote', via: :put
      match 'downvote' => 'posts#downvote', via: :put
      match 'submit', to: 'posts#submit', via: :put
      match 'revert', to: 'posts#revert', via: :put
      match 'approve', to: 'posts#approve', via: :put
      match 'ban', to: 'posts#ban', via: :put
    end



    resources :comments do
      member do
        match 'flag' => 'comments#flag', via: :put
      end
    end

    resources :revisions do
      member do
        patch :pass_off
      end
    end
  end

  match 'flag_comment', to: "comments#flag", via: :put

  resources :voices do
    member do
      match 'upvote' => 'voices#upvote', via: :put
      match 'downvote' => 'voices#downvote', via: :put
    end
  end

  resources :collections, only: [:create, :destroy, :index]

  get 'tags/:keyword', to: 'posts#index', as: :tag

  resources :forums do
    resources :topics
  end

  resources :topics do
    resources :submissions
  end

  resources :invitations

  match 'admin', to: 'admin#index', via: :get

  root 'static_pages#front_page'
end

app/models/category.rb
class Category < ActiveRecord::Base
  searchkick autocomplete: ['title']
  #associations
  belongs_to :parent_category, class_name: Category, foreign_key: 'parent_id'
  has_many :posts, dependent: :destroy
  #validations
  validates :name, presence: true
  validates :description, presence: true
  acts_as_votable
  mount_uploader :picture, CategoryPictureUploader
  include Workflow

  workflow do
    state :draft do
      event :publish, transitions_to: :published
    end

    state :published
  end


  def get_upvotes
    category.posts.get_upvotes.size
  end

  def as_json options={}
    {
        id: id,
        name: name
    }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :find_category, only: [:publish, :downvote, :upvote, :show, :edit, :update, :destroy]

  def new
  end

  def show
    @posts = @category.posts
  end

  def index
    respond_to do |format|
      format.html
      format.json { render json: @categories}
    end
    if params[:query].present?
      @categories = Category.search(params[:query], page: params[:page])
    else
      @categories = Category.order(sort_column + " " + sort_direction)
    end
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to :back
    else
      render 'new'
    end
  end

  def edit
  end

  def upvote
    @category.upvote_by current_user

    if request.xhr?
      render json: { count: @category.get_likes.size, id: params[:id]}
    end
  end

  def downvote
    @category.downvote_by current_user

    if request.xhr?
      render json: { count: @category.get_likes.size, id: params[:id]}
    end
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def publish
    @category.publish!
    flash[:success]= "Category has been published successfully."
    redirect_to :back
  end

  def destroy
    if @category.destroy
      flash[:success] = "Category deleted"
      redirect_to categories_path
    end
  end

private
  def category_params
    params.require(:category).permit(:parent_id, :name, :description, :picture)
  end

  def find_category
    @category = Category.find(params[:id])
  end

  def sort_column
    Category.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/categories/_category.html.haml
%tr[category]
  %td.name= category.name
  %td.vote
  %td
    = link_to upvote_category_path(category), class: 'vote', method: :put, remote: true, id: category.id do
      = fa_icon "sort-asc"
  %td
    %span.votes-count{"data-id" => category.id}
      = category.get_likes.size
  %td
    = link_to downvote_category_path(category), class: 'vote', method: :put, remote: true, id: category.id do
      = fa_icon "sort-down"

app/views/categories/_form.html.haml
= simple_form_for @categories.build do |f|
   = f.input :name
   = f.input :description
   = f.input :picture
   %br
   = f.button :submit

app/views/categories/edit.html.haml
.col-xs-4
  ="edit #{@category.name}"
  ="| #{@category.posts.count} posts"
  =render 'form'

app/views/categories/index.html.haml
.container
  %button.btn.btn-primary.btn-lg{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
    Suggest a new category
  #categories
    .col-md-6
      %input.search{:placeholder => "Search"}/
      %button.sort{"data-sort" => "name"}
        Sort by name
    .col-md-6
      %table
        / IMPORTANT, class="list" have to be at tbody
        %tbody.list
          - @categories.each do |c|
            %tr
              %td.name= c.name
              %td
                = link_to upvote_category_path(c), class: 'vote', method: :put, remote: true, id: c.id do
                  = fa_icon "sort-asc"
              %td
                %span.votes-count{"data-id" => c.id}
                  = c.get_likes.size
              %td
                = link_to downvote_category_path(c), class: 'vote', method: :put, remote: true, id: c.id do
                  = fa_icon "sort-down"


:javascript
  var options = {
    valueNames: [ 'name', 'votes' ]
  };

  var categoryList = new List('categories', options);


/ Button trigger modal

/ Modal
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
          %span.sr-only Close
        %h4#myModalLabel.modal-title
          = "Suggest a new Category"
      .modal-body
        = simple_form_for @categories.build do |f|
          = f.input :name
          = f.input :description
          = f.input :picture
          %br
          = f.button :submit
      .modal-footer

app/views/categories/show.html.haml
.row
  .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
    -@category.posts.each do |post|
      .post-preview
        = link_to post_path(post) do
          %h2.post-title
            = post.title
          %h3.post-subtitle
            = post.brief
        %p.post-meta
          Posted by
          = link_to user_path(post.user.id) do
            #{post.author}
          #{time_ago_in_words(post.updated_at)} ago
      %hr